name: Docker


on:
  # push:
    # Publish `master` as Docker `latest` image.
    # branches:
    #  - release*
    #  - main*

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*


env:
  # TODO: Change variable to your image's name.
  IMAGE: particle-backend

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2
    
    - name: setup jdk11
      uses: actions/setup-java@v2.2.0
      with:
        java-version: 11
        distribution: adopt-hotspot
        
    - uses: actions/cache@v2
      with:
       path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
       key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
       restore-keys: |
         ${{ runner.os }}-gradle-    
         
    - run: chmod +x gradlew        
    
    - name: Build image
      run: bash docker/build.sh
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Push image
      run: |
          IMAGE_ID="${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE"
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "release" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
